import { Playfair } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const playfair= Playfair({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:["400","500"]
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
